# Generated by Django 3.2.3 on 2021-05-22 21:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='luggage',
            fields=[
                ('tag_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('time_stamp', models.DateTimeField(default=datetime.datetime(2021, 5, 22, 16, 29, 34, 930562), verbose_name='Time Last Scanned')),
                ('origin_airport', models.CharField(max_length=150)),
                ('transit_airport', models.CharField(max_length=150)),
                ('destination_airport', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('Arrived', 'Arrived'), ('In Transit', 'In Transit')], default='n/a', max_length=20)),
                ('flagged', models.CharField(choices=[('N', 'N'), ('Y', 'Y')], default='N', max_length=1)),
                ('digital_signature', models.CharField(choices=[('Approved', 'Approved'), ('Disapproved', 'Disapproved'), ('Waiting', 'Waiting')], default='Waiting', max_length=20)),
            ],
        ),
    ]
