# Generated by Django 3.2.3 on 2021-05-18 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='luggage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('time_stamp', models.DateTimeField(verbose_name='Time Last Scanned')),
                ('origin_airport', models.CharField(max_length=150)),
                ('transit_airport', models.CharField(max_length=150)),
                ('destination_airport', models.CharField(max_length=150)),
            ],
        ),
    ]
