# Generated by Django 3.2.3 on 2021-06-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LuggageTrackerWebApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='airport_name',
            field=models.CharField(default='n/a', max_length=150),
        ),
        migrations.AlterField(
            model_name='luggage',
            name='digital_signature',
            field=models.CharField(choices=[('Awaiting Signature', 'Awaiting Signature'), ('Missing', 'Missing'), ('Delayed', 'Delayed'), ('Approved', 'Approved'), ('Disapproved', 'Disapproved')], default='Awaiting Signature', max_length=50),
        ),
        migrations.AlterField(
            model_name='luggage',
            name='status',
            field=models.CharField(choices=[('Checked In', 'Checked In'), ('In Transit', 'In Transit'), ('Arrived At Destination', 'Arrived At Destination'), ('Retrieved', 'Retrieved')], default='Checked In', max_length=30),
        ),
    ]
