# Generated by Django 3.2.3 on 2021-05-18 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LuggageTrackerWebApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='luggage',
            name='tag_id',
        ),
    ]
