# Generated by Django 3.2.3 on 2021-05-18 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LuggageTrackerWebApp', '0002_remove_luggage_tag_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LuggageBlockchain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='Time Last Scanned')),
            ],
        ),
    ]
