# Generated by Django 3.2.3 on 2021-05-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LuggageTrackerWebApp', '0003_luggageblockchain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='luggage',
            old_name='id',
            new_name='tag_id',
        ),
        migrations.RenameField(
            model_name='luggageblockchain',
            old_name='id',
            new_name='tag_id',
        ),
        migrations.AddField(
            model_name='luggageblockchain',
            name='hash_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='luggageblockchain',
            name='prev_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
