# Generated by Django 3.2.3 on 2021-05-19 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LuggageTrackerWebApp', '0004_auto_20210519_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luggageblockchain',
            name='timestamp',
            field=models.DateTimeField(verbose_name='Time Last Scanned'),
        ),
    ]
