# Generated by Django 3.2.3 on 2021-05-20 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LuggageTrackerWebApp', '0006_auto_20210520_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luggageblockchain',
            name='hash_id',
            field=models.CharField(default='AWAITING HASH', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='luggageblockchain',
            name='prev_hash_id',
            field=models.CharField(default='AWAITING HASH', max_length=255, null=True),
        ),
    ]
