# Generated by Django 3.2.3 on 2021-05-21 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LuggageTrackerWebApp', '0007_auto_20210520_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='luggageblockchain',
            name='hash_id',
        ),
        migrations.RemoveField(
            model_name='luggageblockchain',
            name='prev_hash_id',
        ),
    ]
