# Generated by Django 3.2.3 on 2021-05-21 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LuggageTrackerWebApp', '0008_auto_20210521_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='luggageblockchain',
            name='destination_airport',
        ),
        migrations.RemoveField(
            model_name='luggageblockchain',
            name='digital_signature',
        ),
        migrations.RemoveField(
            model_name='luggageblockchain',
            name='flagged',
        ),
        migrations.RemoveField(
            model_name='luggageblockchain',
            name='memo',
        ),
        migrations.RemoveField(
            model_name='luggageblockchain',
            name='name',
        ),
        migrations.RemoveField(
            model_name='luggageblockchain',
            name='origin_airport',
        ),
    ]
