# Generated by Django 3.2.3 on 2021-05-21 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LuggageTrackerWebApp', '0009_auto_20210521_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='luggageblockchain',
            name='name',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
