# Generated by Django 3.2.3 on 2021-05-21 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LuggageTrackerWebApp', '0010_luggageblockchain_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='luggageblockchain',
            name='timestamp',
        ),
    ]
