# Generated by Django 3.2.3 on 2021-05-21 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LuggageTrackerWebApp', '0011_remove_luggageblockchain_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='luggageblockchain',
            name='transit',
            field=models.CharField(choices=[('P', 'PENDING'), ('T', 'TRANSIT'), ('A', 'ARRIVED')], default='P', max_length=1),
        ),
    ]
